# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Gametopia' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Gametopia
  pod 'Alamofire'
  pod 'SwiftyJSON'
  pod 'AlamofireObjectMapper'
  pod 'Kingfisher', '~> 7.0'
  pod 'SkeletonView'
  pod 'SwiftyGif'

  target 'GametopiaTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GametopiaUITests' do
    # Pods for testing
  end

end
